services:
  app:
    container_name: yii3_web
    build:
      dockerfile: docker/Dockerfile
      context: ..
      target: dev
      args:
        USER_ID: ${UID}
        GROUP_ID: ${GID}
    env_file:
      - path: ./dev/.env
      - path: ./dev/override.env
        required: false
    ports:
      - "${DEV_PORT:-80}:80"
    volumes:
      - ../:/app
      - ../runtime:/app/runtime
      - caddy_data:/data
      - caddy_config:/config
    tty: true
  db:
    container_name: yii3_mysql
    image: mysql:latest
    command: --sort_buffer_size=512K
    restart: unless-stopped
    volumes:
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    env_file:
      - ./dev/.mysql
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE

  phpmyadmin:
    container_name: yii3_phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
        - '8887:80'
    environment:
        # - PMA_ARBITRARY=1
        - PMA_HOST=yii3_mysql
    depends_on:
        - db
